// app/layout.tsx
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import ClientSessionProvider from "./layout.client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Calendrier culturel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClientSessionProvider>
        <body id="__next">
          <NavBar />
          {children}
        </body>
      </ClientSessionProvider>
    </html>
  );
}




